name: trotro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - black
  - pytest
  - pytest-cov
  - pandas
  - numpy
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - ipython
  - pyarrow
  - xgboost
  - mlflow
  - hyperopt
  - pip:
    - pickle5
    - azure-ai-ml
    - azure-mlflow
    - pylint
    - pytest
    - isort
    - gunicorn
    - flask
