name: Orchestrate Machine Learning Pipeline

on: [push]

# Cancel previous workflow runs on new commit to the branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  orchestrate-ml-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
            python-version: '3.10'

      - name: Install python packages
        run: |
          make install

      - name: Code formatting and linting
        run: |
          make test lint

      - name: Orchestrate machine learning pipeline
        id: build-model
        run: |
          cd orchestration
          chmod +x test_ml_pipeline.sh
          ./test_ml_pipeline.sh

      - name: Archive MLflow experiment runs
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-experiment-tracking
          path: orchestration/mlruns/0
          retention-days: 5

  deploy-and-test-model:
    runs-on: ubuntu-latest
    needs: orchestrate-ml-pipeline
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python 3.10
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: Install python packages
          run: |
            make install

        - name: Deploy model as web service with docker
          run: |
            make run_deployment_container

        - name: test model
          run : |
            cd deployment
            python  call_predict.py
