name: Install, build and test code

on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
            python-version: '3.10'

      - name: Install python packages
        run: |
          make install

      - name: Code formatting and linting
        run: |
          make test lint
      
      - name: Build machine learning pipeline
        id: build-model
        run: |
          cd orchestration
          chmod +x test_ml_pipeline.sh
          runId = $(./test_ml_pipeline.sh)
          echo "MLFLOW_RUN_ID=$runId" >> $GITHUB_OUTPUT

      - name: Save model as artefact
        run: |
          echo "mlflow run Id from previous step ${{steps.build-model.outputs.MLFLOW_RUN_ID}}"
      

