name: Install, build and test code

on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
            python-version: '3.10'

      - name: Install python packages
        run: |
          make install

      - name: Code formatting and linting
        run: |
          make test lint
      
      - name: Build machine learning pipleine
        run: |
          cd orchestration
          chmod +x test_ml_pipeline.sh
          ./test_ml_pipeline.sh
      

